export const CHANGE_JISHU = 'CHANGE_JISHU'
export const CHANGE_JIXIAO = 'CHANGE_JIXIAO'
export const CHANGE_JIANGJIN = 'CHANGE_JIANGJIN'

export const UPDATE_YANGLAO = 'UPDATE_YANGLAO'
export const UPDATE_YILIAO = 'UPDATE_YILIAO'
export const UPDATE_SHIYE = 'UPDATE_SHIYE'
export const UPDATE_GONGSHANG = 'UPDATE_GONGSHANG'
export const UPDATE_SHENGYU = 'UPDATE_SHENGYU'
export const UPDATE_GONGJIJIN = 'UPDATE_GONGJIJIN'
export const UPDATE_TONGCHOU = 'UPDATE_TONGCHOU'

export const IS_SHOW = 'IS_SHOW'